import { rawExpression } from '../../utils';

describe('NO DICTIONARY/NO DEFAULTS', () => {
  test('Parsing', () => {
    expect(rawExpression('')).toMatchInlineSnapshot(`
      [
        "Sequence"
      ]
    `);
    expect(rawExpression('1+x')).toMatchInlineSnapshot(`
      [
        "Sequence",
        1,
        [
          "Error",
          [
            "ErrorCode",
            "'unexpected-token'",
            "'+'"
          ],
          [
            "LatexString",
            "'+x'"
          ]
        ]
      ]
    `);
    expect(rawExpression('x^2')).toMatchInlineSnapshot(`"x"`);
    expect(rawExpression('\\frac{1}{x}')).toMatchInlineSnapshot(`
      [
        "Error",
        [
          "ErrorCode",
          "'unexpected-command'",
          "'\\\\frac'"
        ],
        [
          "LatexString",
          "'\\\\frac{1}{x}'"
        ]
      ]
    `);
    expect(rawExpression('\\sqrt{(1+x_0)}=\\frac{\\pi^2}{2}'))
      .toMatchInlineSnapshot(`
      [
        "Sequence",
        [
          "Error",
          [
            "ErrorCode",
            "'unexpected-command'",
            "'\\\\sqrt'"
          ],
          [
            "LatexString",
            "'\\\\sqrt{(1+x_0)}'"
          ]
        ],
        [
          "Error",
          [
            "ErrorCode",
            "'unexpected-token'",
            "'='"
          ],
          [
            "LatexString",
            "'=\\\\frac{\\\\pi^2}{2}'"
          ]
        ]
      ]
    `);
  });
});
