/**
 * Example: Compiling mathematical expressions to Python/NumPy code
 *
 * This example demonstrates how to use the Python compilation target
 * to generate NumPy code from mathematical expressions.
 */

import { ComputeEngine } from '@cortex-js/compute-engine';

// NOTE: PythonTarget is not exported from the package.
// This import path works only when running from source with tsx.
import { PythonTarget } from '../src/compute-engine/compilation/python-target';

const ce = new ComputeEngine();
const python = new PythonTarget({ includeImports: true });

console.log('=== Python/NumPy Code Generation Examples ===\n');

// Example 1: Simple expressions
console.log('1. Simple Expressions');
console.log('   LaTeX: x^2 + y^2');
const expr1 = ce.parse('x^2 + y^2');
console.log('   Python:', python.compile(expr1));
console.log();

// Example 2: Trigonometric functions
console.log('2. Trigonometric Functions');
console.log('   LaTeX: \\sin(x) + \\cos(y)');
const expr2 = ce.parse('\\sin(x) + \\cos(y)');
console.log('   Python:', python.compile(expr2));
console.log();

// Example 3: Complex polynomial
console.log('3. Polynomial');
console.log('   LaTeX: x^4 + 3x^3 + 2x^2 + x + 1');
const expr3 = ce.parse('x^4 + 3x^3 + 2x^2 + x + 1');
console.log('   Python:', python.compile(expr3));
console.log();

// Example 4: Nested square roots
console.log('4. Nested Expressions');
console.log('   LaTeX: \\sqrt{x^2 + y^2 + z^2}');
const expr4 = ce.parse('\\sqrt{x^2 + y^2 + z^2}');
console.log('   Python:', python.compile(expr4));
console.log();

// Example 5: Function generation
console.log('5. Function Generation');
console.log('   LaTeX: \\sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}');
const expr5 = ce.parse('\\sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}');
const func = python.compileFunction(
  expr5,
  'euclidean_distance',
  ['x_1', 'y_1', 'x_2', 'y_2'],
  'Calculate Euclidean distance between two points'
);
console.log(func);
console.log();

// Example 6: Quadratic formula
console.log('6. Quadratic Formula');
console.log('   LaTeX: \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}');
const expr6 = ce.parse('\\frac{-b + \\sqrt{b^2 - 4ac}}{2a}');
const quadratic = python.compileFunction(
  expr6,
  'quadratic_root',
  ['a', 'b', 'c'],
  'Calculate one root of a quadratic equation ax^2 + bx + c = 0'
);
console.log(quadratic);
console.log();

// Example 7: Gaussian function
console.log('7. Gaussian (Normal) Distribution');
console.log('   LaTeX: e^{-x^2}');
const expr7 = ce.parse('e^{-x^2}');
const gaussian = python.compileFunction(
  expr7,
  'gaussian',
  ['x'],
  'Unnormalized Gaussian function'
);
console.log(gaussian);
console.log();

// Example 8: Lambda function
console.log('8. Lambda Function');
console.log('   LaTeX: x^2 + 2x + 1');
const expr8 = ce.parse('x^2 + 2x + 1');
const lambda = python.compileLambda(expr8, ['x']);
console.log('   Lambda:', lambda);
console.log();

// Example 9: Physics - Kinematic equation
console.log('9. Physics - Position with Constant Acceleration');
console.log('   LaTeX: s = ut + \\frac{1}{2}at^2');
const expr9 = ce.parse('u \\cdot t + \\frac{1}{2} a \\cdot t^2');
const kinematics = python.compileFunction(
  expr9,
  'position',
  ['u', 'a', 't'],
  'Position with initial velocity u, acceleration a, at time t'
);
console.log(kinematics);
console.log();

// Example 10: Statistics - Standard deviation from variance
console.log('10. Statistics - Standard Deviation');
console.log('   LaTeX: \\sigma = \\sqrt{\\frac{\\sum(x - \\mu)^2}{n}}');
// Simplified for demonstration
const expr10 = ce.parse('\\sqrt{s^2}');
const stddev = python.compileFunction(
  expr10,
  'std_from_variance',
  ['s'],
  'Standard deviation from variance s^2'
);
console.log(stddev);
console.log();

// Example 11: Real-world usage example
console.log('11. Complete Python Script Example');
console.log('    Generates a complete Python script for numerical computation');
console.log();

const script = `#!/usr/bin/env python3
"""
Mathematical functions generated by Compute Engine
Compile expressions to NumPy for fast numerical computation
"""

import numpy as np

${python.compileFunction(ce.parse('x^2 + y^2'), 'sum_of_squares', ['x', 'y'], 'Sum of squares')}

${python.compileFunction(ce.parse('\\sqrt{x^2 + y^2}'), 'magnitude', ['x', 'y'], 'Vector magnitude')}

${python.compileFunction(ce.parse('x \\cdot y'), 'dot_product_scalar', ['x', 'y'], 'Dot product (for scalars)')}

if __name__ == '__main__':
    # Example usage with NumPy arrays
    x = np.array([1, 2, 3, 4, 5])
    y = np.array([5, 4, 3, 2, 1])

    print("Sum of squares:", sum_of_squares(x, y))
    print("Magnitude:", magnitude(x, y))
    print("Dot product:", dot_product_scalar(x, y))
`;

console.log(script);
console.log();

console.log('=== Use Cases ===');
console.log('1. Scientific Computing: Generate NumPy code for numerical analysis');
console.log('2. Machine Learning: Create feature engineering functions');
console.log('3. Data Analysis: Convert formulas to vectorized operations');
console.log('4. Education: Show Python equivalents of mathematical notation');
console.log('5. Code Generation: Automated function creation from specifications');
console.log();

console.log('=== Next Steps ===');
console.log('• Save generated Python code to .py files');
console.log('• Use with NumPy for fast array operations');
console.log('• Integrate with SciPy for scientific computing');
console.log('• Combine with Pandas for data analysis');
console.log('• Deploy as Jupyter notebook functions');
