export const RESERVED_WORDS = new Set<string>([
  'abstract', // Not in use
  'at', // Not in use
  'and', // Not in use
  'as', // Not in use
  'assert',
  'await', // Not in use
  'begin', // Not in use
  'break', // Not in use
  'case', // Not in use
  'catch', // Not in use
  'class', // Not in use
  'const', // Not in use
  'continue', // Not in use
  'debugger',
  'default', // Not in use
  'delete', // Not in use
  'dynamic', // Not in use
  'do', // Not in use
  'each', // Not in use
  'else',
  'end', // Not in use
  'export', // Not in use
  'extern', // Not in use
  'finally', // Not in use
  'for', // Not in use
  'from', // Not in use
  'function', // Not in use
  'get', // Not in use
  'global', // Not in use
  'goto', // Not in use
  'if',
  'in', // Not in use
  'inline', // Not in use
  'interface', // Not in use
  'internal', // Not in use
  'import', // Not in use
  'label', // Not in use
  'lazy', // Not in use
  'local', // Not in use
  'loop', // Not in use
  'match', // Not in use
  'module', // Not in use
  'namespace', // Not in use
  'native', // Not in use
  'new', // Not in use
  'not', // Not in use
  'of', // Not in use
  'on', // Not in use
  'optional', // Not in use
  'or', // Not in use
  'package', // Not in use
  'private', // Not in use
  'protected', // Not in use
  'protocol', // Not in use
  'public', // Not in use
  'repeat', // Not in use
  'return', // Not in use
  'self', // Not in use
  'set', // Not in use
  'static', // Not in use
  'super', // Not in use
  'switch', // Not in use
  'this', // Not in use
  'throw', // Not in use
  'to', // Not in use
  'try', // Not in use
  'until', // Not in use
  'using', // Not in use
  'var', // Not in use
  'warn', // Not in use
  'when', // Not in use
  'where', // Not in use
  'while', // Not in use
  'with', // Not in use
  'xor', // Not in use
  'yield', // Not in use
]);
